#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,      ,             tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("joystickSimple");
#include "JoystickDriver.c"
void tankdrive()
{
	int threshold = 6; // Int 'threshold' will allow us to ignore low  readings that keep our robot in perpetual motion.
		if(abs(joystick.joy1_y2) > threshold)   // If the right analog stick's Y-axis readings are either above or below the threshold:
		{
		motor[motorE] = joystick.joy1_y2;         // Motor D is assigned a power level equal to the right analog stick's Y-axis reading.
		}
		else                                    // Else if the readings are within the threshold:
		{
		motor[motorE] = 0;                        // Motor D is stopped with a power level of 0.
		}


		if(abs(joystick.joy1_y1) > threshold)   // If the left analog stick's Y-axis readings are either above or below the threshold:
		{
		motor[motorD] = joystick.joy1_y1;         // Motor E is assigned a power level equal to the left analog stick's Y-axis reading.
		}
		else                                    // Else if the readings are within the threshold:
		{
		motor[motorD] = 0;                        // Motor E is stopped with a power level of 0.
		}
}
void servoarm()
{
	int threshold = 6; // Int 'threshold' will allow us to ignore low  readings that keep our robot in perpetual motion.
		if(abs(joystick.joy1_y2) > threshold)   // If the right analog stick's Y-axis readings are either above or below the threshold:
		{
		servo[servo1] = joystick.joy1_y2;         // Motor D is assigned a power level equal to the right analog stick's Y-axis reading.
		}
		else                                    // Else if the readings are within the threshold:
		{
		servo[servo1] = 250;                        // Motor D is stopped with a power level of 0.
		}
		//.................................................................................................................
		if(abs(joystick.joy1_x1) > threshold)   // If the left analog stick's Y-axis readings are either above or below the threshold:
		{
		servo[servo2] = joystick.joy1_x1;         // Motor E is assigned a power level equal to the left analog stick's Y-axis reading.
		}
		else                                    // Else if the readings are within the threshold:
		{
	  servo[servo2] = 150;                        // Motor E is stopped with a power level of 0.
		}
}
task main()
{
		while(true)                            // Infinite loop:
		{
			if(joy1Btn(5))
			{
				tankdrive();
			}
			else{}
			if(joy1Btn(6))
			{
				servoarm();
			}
			else{}
		}//ends while statement.\\you can place another statement to continue buildiTICng on your task main
}// ends task main.\\you cannot write more code after this right bracket

//getJoystickSettings(joystick);
//if(joystick.joy1_TopHat == 0)  // If the right analog stick's Y-axis readings are either above or below the threshold:
//{
//servo[servo3] =  60 ;
//}
//if(joystick.joy1_TopHat == 4)
//{
//servo[servo3]  = 235;
//}
//	// BUTTONS TO CONTOL SERVO ARM
//	// Control arm via shoulder buttons, 5 and 6... 5=up, 6=down 7 = extreme down button 8=extreme up/ in
//	//...............................................................................................................................................//
//	if(joy1Btn(2))         // If Button 3 is pressed:"A button" green
//	{
//	servo[servo2] = 10;   // Lower Servo 1 to position down and in.
//	}
//	if(joy1Btn(4))         // If Button 1 is pressed:"Y button" yellow
//	{
//	servo[servo2] = 200;   //Raise Servo 1 to position up.
//	}// matches last left bracket to end that funtion.\\you can place more code after it
