#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     Ultrasonic,     sensorSONAR)
#pragma config(Sensor, S4,     Accel,          sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task reportAccel()
{while(true)
	{
	nxtDisplayString(1,"");
	//wait1Msec(10);
		nxtDisplayString(1, "accel=(%d)", SensorValue[Accel]);// prints a message on the
	}
}
void resetsensor()
{
	SensorValue[Accel]=0;

	return;
}
task main()
{
resetsensor();
	StartTask(reportAccel);
}
