#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRSeeker,       sensorHiTechnicIRSeeker600)
#pragma config(Sensor, S3,     Rotation,       sensorRotation)
#pragma config(Sensor, S4,     Ultrasonic,     sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int nShaftEncoder=SensorValue[S3];
task main()
{
	SensorValue[S3]=0;
	while (true)
			{
		 if(nShaftEncoder<30)
			{
				motor[lift]=15;
			}
			else{	motor[lift]=0;}
}
}
