#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     IRSeeker,       sensorHiTechnicIRSeeker600)
#pragma config(Sensor, S3,     Ultrasonic,     sensorRotation)
#pragma config(Sensor, S4,     Rotation,       sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task reportRotations()
{while(true)
	{
		int RotationRCX=SensorValue[S3];
	nxtDisplayString(1,"");//clear screen
	wait1Msec(10);// refresh readings
		nxtDisplayString(1, "rotation=(%f)", RotationRCX);// prints a message on the nxt screen
	}
}
void reset()
{
	RotationRCX=0;
	return;
}
task main()
{
	reset()
StartTask(reportRotations);
}
